apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hura
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0009-tenant/ci10t-777-0009-app/devfile-sample-hura@sha256:a3fe577135a5d6b836174fb57d7c4a5836dd95435a0893c71d84fabd609c4bba
        name: my-nodejs
        resources: {}
status: {}
